theme: jekyll-theme-minimal
title: carlos kynäslahti's new homepage
description: hey there, im making a new website you can still check the old one at [http://52.212.39.194/](http://52.212.39.194/) - carlos
